export const mockSkills = [
  "Three.js", "React.js", "WebGL", "Java", "Spring Boot",
  "TypeScript", "Tailwind CSS", "PostgreSQL", "Next.js", "Python",
  "Machine Learning", "Docker", "AWS", "Figma", "UI/UX Design",
  "Flutter", "GraphQL", "Kubernetes", "Node.js", "Stripe API"
];

export const mockUsers = [
  {
    id: 1,
    email: "admin@freelancehub.com",
    fullName: "System Administrator",
    role: "ROLE_ADMIN",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    location: "San Francisco, CA",
    timezone: "PST (UTC-8)",
    emailVerified: true,
    phoneVerified: true,
    identityVerified: true,
    isSuspended: false
  },
  {
    id: 2,
    email: "client@techcorp.com",
    fullName: "Sarah Jenkins",
    role: "ROLE_CLIENT",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    location: "New York, NY",
    timezone: "EST (UTC-5)",
    emailVerified: true,
    phoneVerified: true,
    identityVerified: true,
    isSuspended: false,
    companyName: "TechCorp Ventures",
    totalSpent: 48500.00,
    projectsPostedCount: 5,
    hiresCount: 8,
    rating: 4.9
  },
  {
    id: 3,
    email: "elena@freelancehub.com",
    fullName: "Elena Vance",
    role: "ROLE_FREELANCER",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    location: "Seattle, WA",
    timezone: "PST (UTC-8)",
    emailVerified: true,
    phoneVerified: true,
    identityVerified: true,
    isSuspended: false,
    title: "Lead 3D WebGL & Three.js Creative Technologist",
    hourlyRate: 85,
    projectBaseRate: 2500,
    availability: "AVAILABLE_FULL_TIME",
    rating: 5.0,
    totalReviewsCount: 42,
    completedProjectsCount: 48,
    successRate: 99.0,
    responseTimeHours: 1,
    skills: ["Three.js", "WebGL", "React.js", "TypeScript", "Tailwind CSS"]
  }
];

export const mockFreelancers = [
  {
    id: 1,
    userId: 3,
    fullName: "Elena Vance",
    email: "elena@freelancehub.com",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    location: "Seattle, WA",
    timezone: "PST (UTC-8)",
    identityVerified: true,
    title: "Lead 3D WebGL & Three.js Creative Technologist",
    overview: "Specializing in high-performance WebGL 3D visualizations, interactive product configurators, and shader magic for top global brands. Over 8 years of experience engineering immersive spatial web experiences with React Three Fiber, GLSL, and WebGPU.",
    hourlyRate: 85,
    projectBaseRate: 2500,
    availability: "AVAILABLE_FULL_TIME",
    languages: "English (Native), French (Fluent)",
    responseTimeHours: 1,
    experienceYears: 8,
    completedProjectsCount: 48,
    successRate: 99.0,
    rating: 5.0,
    totalReviewsCount: 42,
    skills: ["Three.js", "WebGL", "React.js", "TypeScript", "Tailwind CSS"],
    portfolioItems: [
      {
        id: 1,
        title: "Cyberpunk 3D Hologram City",
        description: "Interactive procedural city generator running 60fps in WebGL with custom bloom shaders.",
        imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=500&auto=format&fit=crop&q=80",
        projectUrl: "https://threejs-demo.freelancehub3d.com",
        tags: "Three.js, WebGL, GLSL"
      },
      {
        id: 2,
        title: "Spatial 3D Watch Configurator",
        description: "Real-time luxury watch customization portal featuring PBR materials and environment lighting.",
        imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=80",
        projectUrl: "https://configurator-demo.freelancehub3d.com",
        tags: "React Three Fiber, PBR"
      }
    ]
  },
  {
    id: 2,
    userId: 4,
    fullName: "Alex Chen",
    email: "alex@freelancehub.com",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    location: "Vancouver, Canada",
    timezone: "PST (UTC-8)",
    identityVerified: true,
    title: "Principal Full-Stack Architect (Spring Boot & React)",
    overview: "Architecting enterprise-scale distributed systems, mission-critical REST microservices, real-time WebSocket infrastructures, and robust React frontend web applications.",
    hourlyRate: 95,
    projectBaseRate: 3500,
    availability: "AVAILABLE_FULL_TIME",
    languages: "English (Fluent), Mandarin (Native)",
    responseTimeHours: 2,
    experienceYears: 10,
    completedProjectsCount: 62,
    successRate: 100.0,
    rating: 4.9,
    totalReviewsCount: 55,
    skills: ["Java", "Spring Boot", "React.js", "PostgreSQL", "Docker", "AWS"],
    portfolioItems: []
  },
  {
    id: 3,
    userId: 5,
    fullName: "Priya Sharma",
    email: "priya@freelancehub.com",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    location: "London, UK",
    timezone: "GMT (UTC+0)",
    identityVerified: true,
    title: "AI & GenAI Solutions Engineer | LLMs & RAG",
    overview: "Designing bespoke Generative AI agents, vector retrieval pipelines, fine-tuned LLM architectures, and seamless Python/Spring backend integrations.",
    hourlyRate: 110,
    projectBaseRate: 4000,
    availability: "AVAILABLE_PART_TIME",
    languages: "English (Fluent), Hindi (Native)",
    responseTimeHours: 1,
    experienceYears: 6,
    completedProjectsCount: 34,
    successRate: 100.0,
    rating: 5.0,
    totalReviewsCount: 29,
    skills: ["Python", "Machine Learning", "AWS", "Docker", "PostgreSQL"],
    portfolioItems: []
  },
  {
    id: 4,
    userId: 6,
    fullName: "Marcus Rossi",
    email: "marcus@freelancehub.com",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    location: "Milan, Italy",
    timezone: "CET (UTC+1)",
    identityVerified: true,
    title: "Senior Product Designer & Design Systems Lead",
    overview: "Designing sleek, modern, futuristic SaaS interfaces and design systems. Former design lead at European fintech unicorn.",
    hourlyRate: 75,
    projectBaseRate: 2000,
    availability: "AVAILABLE_FULL_TIME",
    languages: "English (Fluent), Italian (Native)",
    responseTimeHours: 2,
    experienceYears: 7,
    completedProjectsCount: 51,
    successRate: 98.0,
    rating: 4.9,
    totalReviewsCount: 44,
    skills: ["Figma", "UI/UX Design", "Tailwind CSS", "React.js"],
    portfolioItems: []
  },
  {
    id: 5,
    userId: 7,
    fullName: "David Okafor",
    email: "david@freelancehub.com",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    location: "Lagos, Nigeria",
    timezone: "WAT (UTC+1)",
    identityVerified: false,
    title: "Cross-Platform Mobile Flutter Engineer",
    overview: "Building fast, fluid iOS and Android apps with Flutter, Firebase, and GraphQL.",
    hourlyRate: 65,
    projectBaseRate: 1800,
    availability: "AVAILABLE_FULL_TIME",
    languages: "English (Fluent)",
    responseTimeHours: 3,
    experienceYears: 5,
    completedProjectsCount: 22,
    successRate: 97.0,
    rating: 4.8,
    totalReviewsCount: 19,
    skills: ["Flutter", "GraphQL", "React.js", "Node.js"],
    portfolioItems: []
  }
];

export const mockProjects = [
  {
    id: 1,
    clientId: 2,
    clientName: "Sarah Jenkins",
    clientEmail: "client@techcorp.com",
    clientAvatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    clientCompany: "TechCorp Ventures",
    clientVerified: true,
    clientRating: 4.9,
    title: "Next-Gen 3D Interactive Metaverse Showcase",
    description: "We are looking for an elite 3D WebGL developer to build a futuristic, interactive 3D hero showcase for our upcoming fintech platform. Must support WebGL shaders, particle simulations, camera panning on scroll, and mobile responsive optimization.",
    category: "3D & Graphics",
    budgetType: "FIXED",
    budgetMin: 3000,
    budgetMax: 5000,
    experienceLevel: "EXPERT",
    estimatedDurationDays: 21,
    deadline: "2026-09-15",
    status: "IN_PROGRESS",
    proposalsCount: 3,
    requiredSkills: ["Three.js", "WebGL", "React.js", "TypeScript"],
    createdAt: "2026-08-10T10:00:00"
  },
  {
    id: 2,
    clientId: 2,
    clientName: "Sarah Jenkins",
    clientEmail: "client@techcorp.com",
    clientAvatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    clientCompany: "TechCorp Ventures",
    clientVerified: true,
    clientRating: 4.9,
    title: "Enterprise Distributed Microservices Migration",
    description: "Migrate legacy monolith to resilient Spring Boot 3 microservices with PostgreSQL, Docker containerization, and AWS ECS deployment. Need full automated unit and integration test coverage.",
    category: "Web Development",
    budgetType: "FIXED",
    budgetMin: 6000,
    budgetMax: 9000,
    experienceLevel: "EXPERT",
    estimatedDurationDays: 45,
    deadline: "2026-10-01",
    status: "OPEN",
    proposalsCount: 2,
    requiredSkills: ["Java", "Spring Boot", "PostgreSQL", "Docker", "AWS"],
    createdAt: "2026-08-14T14:30:00"
  },
  {
    id: 3,
    clientId: 8,
    clientName: "Robert Vance",
    clientEmail: "client2@nexus.io",
    clientAvatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    clientCompany: "Nexus Dynamics",
    clientVerified: true,
    clientRating: 5.0,
    title: "Fintech SaaS UI/UX Overhaul & Modern Design System",
    description: "Complete redesign of our web app dashboard and user flows. Deliver pixel-perfect Figma components, design tokens, responsive guidelines, and interactive clickable prototypes.",
    category: "UI/UX Design",
    budgetType: "FIXED",
    budgetMin: 2500,
    budgetMax: 4000,
    experienceLevel: "INTERMEDIATE",
    estimatedDurationDays: 14,
    deadline: "2026-09-05",
    status: "OPEN",
    proposalsCount: 1,
    requiredSkills: ["Figma", "UI/UX Design", "Tailwind CSS"],
    createdAt: "2026-08-16T09:15:00"
  }
];

export const mockContracts = [
  {
    id: 1,
    projectId: 1,
    projectTitle: "Next-Gen 3D Interactive Metaverse Showcase",
    proposalId: 1,
    clientId: 2,
    clientName: "Sarah Jenkins",
    clientEmail: "client@techcorp.com",
    clientAvatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    freelancerId: 3,
    freelancerName: "Elena Vance",
    freelancerEmail: "elena@freelancehub.com",
    freelancerAvatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    title: "Next-Gen 3D Interactive Metaverse Showcase",
    totalAmount: 4500.00,
    paidAmount: 1500.00,
    escrowAmount: 3000.00,
    status: "ACTIVE",
    startDate: "2026-08-12",
    endDate: "2026-09-02",
    milestones: [
      {
        id: 1,
        contractId: 1,
        title: "Milestone 1: 3D Scene Architecture & Asset Shaders",
        description: "Setup Three.js canvas, lighting, camera controls, and custom procedural shaders.",
        amount: 1500.00,
        milestoneOrder: 1,
        dueDate: "2026-08-16",
        status: "PAID",
        submissionNotes: "Completed 3D scene architecture, particle systems, and shader pipelines.",
        deliverablesUrl: "https://github.com/techcorp/3d-scene-v1",
        submittedAt: "2026-08-15T18:00:00",
        approvedAt: "2026-08-16T11:20:00",
        paidAt: "2026-08-16T11:20:00"
      },
      {
        id: 2,
        contractId: 1,
        title: "Milestone 2: Interactive Animations & Scroll Reactivity",
        description: "Implement smooth camera panning, hover interactivity, and state transitions.",
        amount: 1500.00,
        milestoneOrder: 2,
        dueDate: "2026-08-25",
        status: "IN_PROGRESS"
      },
      {
        id: 3,
        contractId: 1,
        title: "Milestone 3: Final Polish, Mobile Optimization & Delivery",
        description: "LOD optimizations, responsive canvas scaling, and deployment.",
        amount: 1500.00,
        milestoneOrder: 3,
        dueDate: "2026-09-02",
        status: "PENDING"
      }
    ]
  }
];

export const mockMessages = [
  {
    id: 1,
    senderId: 2,
    senderName: "Sarah Jenkins",
    senderAvatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    recipientId: 3,
    recipientName: "Elena Vance",
    content: "Hi Elena! Welcome aboard. We're very excited to see the 3D scene come together!",
    isRead: true,
    createdAt: "2026-08-12T14:20:00"
  },
  {
    id: 2,
    senderId: 3,
    senderName: "Elena Vance",
    senderAvatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    recipientId: 2,
    recipientName: "Sarah Jenkins",
    content: "Thanks Sarah! I've already set up the initial WebGL scene with particle nodes and lighting. Milestone 1 deliverables are ready for your review!",
    isRead: true,
    createdAt: "2026-08-15T18:05:00"
  },
  {
    id: 3,
    senderId: 2,
    senderName: "Sarah Jenkins",
    senderAvatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    recipientId: 3,
    recipientName: "Elena Vance",
    content: "The performance is breathtaking! I've just approved Milestone 1 and released the payment. Keep up the amazing work!",
    isRead: false,
    createdAt: "2026-08-16T11:22:00"
  }
];

export const mockNotifications = [
  {
    id: 1,
    title: "Milestone 1 Payment Released",
    message: "Client Sarah Jenkins approved Milestone 1. $1,500.00 has been transferred to your earnings balance.",
    type: "PAYMENT_SUCCESS",
    linkUrl: "/contracts/1",
    isRead: false,
    createdAt: "2026-08-16T11:22:00"
  },
  {
    id: 2,
    title: "New Proposal Received",
    message: "Elena Vance submitted a proposal for 'Next-Gen 3D Interactive Metaverse Showcase' ($4,500.00)",
    type: "NEW_PROPOSAL",
    linkUrl: "/proposals?project=1",
    isRead: true,
    createdAt: "2026-08-11T09:12:00"
  }
];

export const mockTransactions = [
  {
    id: 1,
    contractId: 1,
    contractTitle: "Next-Gen 3D Interactive Metaverse Showcase",
    milestoneId: 1,
    milestoneTitle: "Milestone 1: 3D Scene Architecture & Asset Shaders",
    payerName: "Sarah Jenkins",
    payeeName: "Elena Vance",
    amount: 1500.00,
    currency: "USD",
    paymentMethod: "CREDIT_CARD",
    paymentGateway: "STRIPE",
    gatewayOrderId: "ORD_STR_9812471923",
    status: "SUCCESS",
    receiptUrl: "https://receipts.freelancehub3d.com/rec_001.pdf",
    createdAt: "2026-08-16T11:20:00"
  },
  {
    id: 2,
    contractId: 1,
    contractTitle: "Next-Gen 3D Interactive Metaverse Showcase",
    milestoneId: 2,
    milestoneTitle: "Milestone 2: Interactive Animations & Scroll Reactivity",
    payerName: "Sarah Jenkins",
    payeeName: "Elena Vance",
    amount: 1500.00,
    currency: "USD",
    paymentMethod: "CREDIT_CARD",
    paymentGateway: "STRIPE",
    gatewayOrderId: "ORD_STR_9812471924",
    status: "SUCCESS",
    receiptUrl: "https://receipts.freelancehub3d.com/rec_002.pdf",
    createdAt: "2026-08-12T14:00:00"
  }
];
